// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6wl6aQaGB53jI3CuGfn0XPbKI0RXClr4',
    appId: '1:268628055544:android:3e702a54e0eb7eab4cb20d',
    messagingSenderId: '268628055544',
    projectId: 'wizz-2886a',
    storageBucket: 'wizz-2886a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH7jzaTq1GiJyYMlLjEFPtSoxmMWR049w',
    appId: '1:268628055544:ios:0b04553ebe0a4b874cb20d',
    messagingSenderId: '268628055544',
    projectId: 'wizz-2886a',
    storageBucket: 'wizz-2886a.firebasestorage.app',
    iosClientId: '268628055544-rkj6r0pjrca7mp2h5k46kho0u243rgh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.wizz',
  );


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtxmHcVv0eIJJi23Zebz1LBXcJwHATa2U',
    appId: '1:268628055544:web:a00b90a3c1b8ffe04cb20d',
    messagingSenderId: '268628055544',
    projectId: 'wizz-2886a',
    authDomain: 'wizz-2886a.firebaseapp.com',
    storageBucket: 'wizz-2886a.firebasestorage.app',
    measurementId: 'G-MP8RKSMSWM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH7jzaTq1GiJyYMlLjEFPtSoxmMWR049w',
    appId: '1:268628055544:ios:0b04553ebe0a4b874cb20d',
    messagingSenderId: '268628055544',
    projectId: 'wizz-2886a',
    storageBucket: 'wizz-2886a.firebasestorage.app',
    iosClientId: '268628055544-rkj6r0pjrca7mp2h5k46kho0u243rgh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.wizz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtxmHcVv0eIJJi23Zebz1LBXcJwHATa2U',
    appId: '1:268628055544:web:463b3a3eca90a88b4cb20d',
    messagingSenderId: '268628055544',
    projectId: 'wizz-2886a',
    authDomain: 'wizz-2886a.firebaseapp.com',
    storageBucket: 'wizz-2886a.firebasestorage.app',
    measurementId: 'G-0MMRG2EZSX',
  );

}